name: jsonio17

dependencies:
  - gxx_linux-64>=9.4.0  # [linux]
  - cmake>=3.7
  - ninja # [unix]
  - make  # [win]
  - git
  - ccache  # [unix]
  - curl
  - nlohmann_json
  - velocypack
  - fmt
  - spdlog>=1.10.0 # [win]
  - spdlog # [unix]
  - jsonarango

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
