
if(${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
find_library(CURL_LIB libcurl)
else()
find_library(CURL_LIB curl)
endif()
if(NOT CURL_LIB)
  message(FATAL_ERROR "curl library not found")
endif()

#find_package(velocypack REQUIRED)
find_library(VELOCYPACK_LIB velocypack)
if(NOT VELOCYPACK_LIB)
  message(FATAL_ERROR "velocypack library not found")
endif()

if(${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
find_library(JSONIO_LIB jsonarango-static)
else()
find_library(JSONIO_LIB jsonarango)
endif()
if(NOT JSONIO_LIB)
  message(FATAL_ERROR "jsonarango library not found")
endif()
