name: ci-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            conda_platform: linux-64
            artifact_name: jsonio-linux
          - os: windows-latest
            conda_platform: win-64
            artifact_name: jsonio-windows
          - os: macos-latest
            conda_platform: osx-64
            artifact_name: jsonio-macos

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          channels: conda-forge, defaults
          channel-priority: true

      - name: Configuring Conda Environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Building, Testing & Installing jsonio
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          conda activate jsonio
          ./conda-install-dependencies.sh
          mkdir .build && cd .build
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
          ninja
          ninja install

      - name: Building, Testing & Installing jsonio (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call conda activate jsonio || goto :eof
          call conda-install-dependencies.bat || goto :eof
          echo "Configuring..." || goto :eof
          cmake -DCMAKE_BUILD_TYPE=Release -A x64 -S . -B build  || goto :eof
          echo "Building..." || goto :eof
          cmake --build build --target install --config Release  || goto :eof

      - name: Check conda
        run: |
          conda list

